-- Subsidio para protese/aparelho auditivo
-- Fluxo baseado no subsidio funeral:
-- atendimento -> financeiro -> diretoria -> financeiro -> finalizado.
--
-- O proprio associado e o solicitante. Por isso nao existem blocos duplicados
-- de solicitante/beneficiario nem campos de parentesco ou renda.

CREATE TABLE DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
  ID_SUBSIDIO_AUDITIVO          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  ST_SOLICITACAO                VARCHAR2(40)
    DEFAULT 'AGUARDANDO_ASSINATURA_SOLICITANTE' NOT NULL,

  DT_SOLICITACAO                DATE DEFAULT SYSDATE NOT NULL,
  NM_USUARIO_ABERTURA           VARCHAR2(150),
  LOGIN_USUARIO_ABERTURA        VARCHAR2(120),

  ID_ASSOCIADO                  NUMBER,
  NR_CPF_ASSOCIADO              VARCHAR2(11) NOT NULL,
  NM_ASSOCIADO                  VARCHAR2(150) NOT NULL,
  NR_MATRICULA_ASSOCIADO        VARCHAR2(50),
  DS_FUNCAO_ASSOCIADO           VARCHAR2(120),
  NM_ORGAO_ASSOCIADO            VARCHAR2(150),
  DT_ASSOCIACAO                 DATE,
  NR_CELULAR                    VARCHAR2(20),
  NR_TELEFONE_RESIDENCIAL       VARCHAR2(20),

  VL_NIVEL_INTEGRALIZACAO       NUMBER(15,2),
  VL_CAPITAL                    NUMBER(15,2),

  DS_ORCAMENTOS                 VARCHAR2(1000),
  VL_CUSTO_APARELHO             NUMBER(15,2),
  VL_SUBSIDIO_APROVADO          NUMBER(15,2),
  NM_PRESTADOR_SERVICO          VARCHAR2(150),
  NR_CPF_CNPJ_PRESTADOR         VARCHAR2(14),
  DS_INFORMACOES_ADICIONAIS     VARCHAR2(1000),
  DT_LIMITE_NOTA_FISCAL         DATE,

  CD_BANCO                      VARCHAR2(20),
  NM_BANCO                      VARCHAR2(100),
  CD_AGENCIA                    VARCHAR2(20),
  NR_CONTA                      VARCHAR2(30),
  TP_CONTA                      VARCHAR2(20),

  DS_MOTIVO_DEVOLUCAO           VARCHAR2(1000),

  DT_ENVIO_DIRETORIA            DATE,
  NM_RESP_DIRETORIA             VARCHAR2(150),
  DT_APROVACAO_DIRETORIA        DATE,

  DT_ENVIO_FINANCEIRO           DATE,
  NM_RESP_FINANCEIRO            VARCHAR2(150),
  DT_FINALIZACAO                DATE,

  DT_CRIACAO                    DATE DEFAULT SYSDATE NOT NULL,
  DT_ATUALIZACAO                DATE,
  SN_ATIVO                      NUMBER(1) DEFAULT 1 NOT NULL,

  CONSTRAINT CK_SUB_AUDITIVO_STATUS CHECK (
    ST_SOLICITACAO IN (
      'RASCUNHO',
      'AGUARDANDO_ASSINATURA_SOLICITANTE',
      'AGUARDANDO_FINANCEIRO',
      'AGUARDANDO_DIRETORIA',
      'DEVOLVIDO_AO_ATENDIMENTO',
      'FINALIZADO',
      'CANCELADO'
    )
  ),

  CONSTRAINT CK_SUB_AUDITIVO_TP_CONTA CHECK (
    TP_CONTA IS NULL
    OR TP_CONTA IN ('CORRENTE', 'POUPANCA')
  ),

  CONSTRAINT CK_SUB_AUDITIVO_ATIVO CHECK (
    SN_ATIVO IN (0, 1)
  ),

  CONSTRAINT CK_SUB_AUDITIVO_VALORES CHECK (
    (VL_NIVEL_INTEGRALIZACAO IS NULL OR VL_NIVEL_INTEGRALIZACAO >= 0)
    AND (VL_CAPITAL IS NULL OR VL_CAPITAL >= 0)
    AND (VL_CUSTO_APARELHO IS NULL OR VL_CUSTO_APARELHO >= 0)
    AND (VL_SUBSIDIO_APROVADO IS NULL OR VL_SUBSIDIO_APROVADO >= 0)
  )
);

CREATE INDEX DBACRESSEM.IX_SUB_AUDITIVO_LOGIN
  ON DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
    UPPER(TRIM(LOGIN_USUARIO_ABERTURA))
  );

CREATE INDEX DBACRESSEM.IX_SUB_AUDITIVO_STATUS
  ON DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
    ST_SOLICITACAO,
    SN_ATIVO
  );

CREATE INDEX DBACRESSEM.IX_SUB_AUDITIVO_CPF
  ON DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
    NR_CPF_ASSOCIADO
  );


CREATE TABLE DBACRESSEM.SUBSIDIO_AUDITIVO_ANEXO (
  ID_SUBSIDIO_AUDITIVO_ANEXO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_SUBSIDIO_AUDITIVO          NUMBER NOT NULL,
  TP_ANEXO                      VARCHAR2(50) NOT NULL,
  NM_ARQUIVO_ORIGINAL           VARCHAR2(255) NOT NULL,
  DS_CAMINHO_ARQUIVO            VARCHAR2(1000) NOT NULL,
  DS_MIME_TYPE                  VARCHAR2(150),
  NR_TAMANHO_BYTES              NUMBER,
  NM_USUARIO_UPLOAD             VARCHAR2(150),
  LOGIN_USUARIO_UPLOAD          VARCHAR2(120),
  DT_UPLOAD                     DATE DEFAULT SYSDATE NOT NULL,
  SN_ATIVO                      NUMBER(1) DEFAULT 1 NOT NULL,

  CONSTRAINT FK_SUB_AUD_ANEXO_SOLICITACAO FOREIGN KEY (
    ID_SUBSIDIO_AUDITIVO
  ) REFERENCES DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
    ID_SUBSIDIO_AUDITIVO
  ),

  CONSTRAINT CK_SUB_AUDITIVO_ANEXO_TIPO CHECK (
    TP_ANEXO IN (
      'DOCUMENTOS_GERAIS',
      'ORCAMENTOS_NOTA_FISCAL',
      'AUTORIZACAO_ASSINADA_SOLICITANTE',
      'AUTORIZACAO_ASSINADA_DIRETORIA'
    )
  ),

  CONSTRAINT CK_SUB_AUDITIVO_ANEXO_ATIVO CHECK (
    SN_ATIVO IN (0, 1)
  )
);

CREATE INDEX DBACRESSEM.IX_SUB_AUDITIVO_ANEXO_SOL
  ON DBACRESSEM.SUBSIDIO_AUDITIVO_ANEXO (
    ID_SUBSIDIO_AUDITIVO,
    SN_ATIVO
  );

-- Garante no maximo um anexo ativo de cada tipo por solicitacao.
CREATE UNIQUE INDEX DBACRESSEM.UX_SUB_AUDITIVO_ANEXO_ATIVO
  ON DBACRESSEM.SUBSIDIO_AUDITIVO_ANEXO (
    CASE WHEN SN_ATIVO = 1 THEN ID_SUBSIDIO_AUDITIVO END,
    CASE WHEN SN_ATIVO = 1 THEN TP_ANEXO END
  );


CREATE TABLE DBACRESSEM.SUBSIDIO_AUDITIVO_HISTORICO (
  ID_SUBSIDIO_AUDITIVO_HIST     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_SUBSIDIO_AUDITIVO          NUMBER NOT NULL,
  ST_ANTERIOR                   VARCHAR2(40),
  ST_NOVO                       VARCHAR2(40) NOT NULL,
  DS_ACAO                       VARCHAR2(80) NOT NULL,
  DS_OBSERVACAO                 VARCHAR2(1000),
  NM_USUARIO                    VARCHAR2(150),
  LOGIN_USUARIO                 VARCHAR2(120),
  DT_ACAO                       DATE DEFAULT SYSDATE NOT NULL,

  CONSTRAINT FK_SUB_AUD_HIST_SOLICITACAO FOREIGN KEY (
    ID_SUBSIDIO_AUDITIVO
  ) REFERENCES DBACRESSEM.SOLICITACAO_SUBSIDIO_AUDITIVO (
    ID_SUBSIDIO_AUDITIVO
  )
);

CREATE INDEX DBACRESSEM.IX_SUB_AUDITIVO_HIST_SOL
  ON DBACRESSEM.SUBSIDIO_AUDITIVO_HISTORICO (
    ID_SUBSIDIO_AUDITIVO,
    DT_ACAO
  );

COMMIT;
