DECLARE
  coluna_existe NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO coluna_existe
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'DBACRESSEM'
     AND TABLE_NAME = 'PATROCINIO'
     AND COLUMN_NAME = 'NM_CONSELHO';

  IF coluna_existe = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE DBACRESSEM.PATROCINIO ADD (NM_CONSELHO VARCHAR2(255))';
  END IF;
END;
/
