export const AD_GROUPS = {
  SUPORTE: "GG_USERS_SUPORTE",
  CADASTRO: "GG_USERS_CAD",
  RH: "GG_USERS_RH",
  FINANCEIRO: "GG_USERS_FIN",
  AGENCIA: "GG_USERS_AGE",
  COBRANCA: "GG_USERS_COB",
  TI: "GG_USERS_TI",
  MARKETING: "GG_USERS_MKT",
  AUDITORIA: "GG_USERS_ANTEC",
  DOCUSIGN: "GG_USERS_DOCUSIGN",
} as const;