export const AUXILIO_CRECHE_TETO = 545.87;

export const AUXILIO_CRECHE_TEXTOS = {
  titulo: "SOLICITAÇÃO DE REEMBOLSO DE AUXÍLIO CRECHE OU BABÁ",
  aviso: "TODO MÊS APRESENTAR AO RH O BOLETO E O COMPROVANTE DE PAGAMENTO.",
};