import { ScreenItem } from "@/components/search-home/search-home";

export const GROUPS = {
  SUPORTE: "GG_USERS_SUPORTE",
  CADASTRO: "GG_USERS_CADASTRO",
  RH: "GG_USERS_RH",
  AUDITORIA: "GG_USERS_AUDITORIA",
  FINANCEIRO: "GG_USERS_FINANCEIRO",
  AGENCIA: "GG_USERS_AGENCIA",
  COBRANCA: "GG_USERS_COBRANCA",
  DOCUSIGN: "GG_USERS_DOCUSIGN",
  CONTRATOS: "GG_USERS_CONTRATOS",
  TI: "GG_USERS_TI",
  MARKETING: "GG_USERS_MARKETING",
  CHEQUE_ESPECIAL: "GG_USERS_CHEQUE_ESPECIAL",
  GERENCIA_DIRETORIA: "GG_USERS_GERENCIA_DIRETORIA",
  ESTOQUE: "GG_USERS_ALMO",
} as const;

export const SCREENS: ScreenItem[] = [
  {
    title: "Home",
    desc: "Página inicial da intranet.",
    href: "/auth/home",
    badge: "início",
    group: "Geral",
    pinned: true,
    keywords: ["inicio", "home", "principal", "pagina inicial"],
  },
  {
    title: "Links Úteis",
    desc: "Central com acessos rápidos para as principais telas da intranet.",
    href: "/auth/links_uteis",
    badge: "novo",
    group: "Geral",
    pinned: true,
    keywords: ["atalhos", "acessos", "links", "util", "úteis", "central"],
  },
  {
    title: "Popup Cadastro",
    desc: "Gerenciar avisos e popups exibidos na intranet.",
    href: "/auth/popup_aviso",
    group: "Comunicação",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["popup", "aviso", "comunicado", "mensagem", "banner"],
  },

  {
    title: "Análise de Limite - Cadastro",
    desc: "Cadastrar análise de limite.",
    href: "/auth/cadastro_analise_limite",
    group: "Crédito",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.AGENCIA],
    keywords: ["analise", "análise", "limite", "cadastro", "credito", "crédito"],
  },
  {
    title: "Análise de Limite - Consulta",
    desc: "Consultar análises de limite cadastradas.",
    href: "/auth/consulta_analise_limite",
    group: "Crédito",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.AGENCIA],
    keywords: ["analise", "análise", "limite", "consulta", "credito", "crédito"],
  },

  {
    title: "Aniversariantes",
    desc: "Ver aniversariantes do dia e do mês.",
    href: "/auth/aniversariantes",
    group: "RH",
    pinned: true,
    keywords: ["rh", "datas", "aniversario", "aniversário", "colaboradores", "funcionarios"],
  },
  {
    title: "Auditoria",
    desc: "Acesso à tela de auditoria.",
    href: "/auth/auditoria",
    group: "Geral",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.AUDITORIA],
    keywords: ["auditoria", "controle", "verificacao", "verificação"],
  },
  {
    title: "Antecipação de Capital",
    desc: "Acesso ao formulário de antecipação de capital.",
    href: "/auth/antecipacao_capital",
    group: "Financeiro",
    keywords: ["capital", "antecipacao", "antecipação", "financeiro", "formulario"],
  },
  {
    title: "Assinatura E-mail",
    desc: "Gerar assinatura de e-mail institucional.",
    href: "/auth/assinatura_email",
    group: "Ferramentas",
    pinned: true,
    keywords: ["assinatura", "email", "e-mail", "institucional", "rodape", "rodapé"],
  },
  {
    title: "Calculadora de Juros Cartão",
    desc: "Calcular juros relacionados a operações com cartão.",
    href: "/auth/calculadora_juros_cartao",
    group: "Ferramentas",
    pinned: true,
    keywords: ["calculadora", "juros", "cartao", "cartão", "simulacao", "simulação"],
  },
  {
    title: "Estoque de Consumíveis",
    desc: "Controle e dê baixa.",
    href: "/auth/estoque_consumiveis",
    group: "Ferramentas",
    pinned: true,
    allowedGroups: [GROUPS.SUPORTE, GROUPS.ESTOQUE],
    keywords: ["estoque", "almoxerifado", "consumiveis", "chamado"],
  },
  {
    title: "Chamados de Estoque",
    desc: "Painel de chamados do GLPI de estoque.",
    href: "/auth/painel_glpi_estoque",
    group: "Ferramentas",
    pinned: true,
    allowedGroups: [GROUPS.SUPORTE, GROUPS.ESTOQUE],
    keywords: ["estoque", "almoxerifado", "consumiveis", "chamado", "monitoramento"],
  },
  {
    title: "Simulador de Investimento",
    desc: "Simular valores de investimento.",
    href: "/auth/simulador_investimento",
    group: "Financeiro",
    pinned: true,
    allowedGroups: [GROUPS.SUPORTE, GROUPS.AGENCIA],
    keywords: ["investimento", "simulador", "aplicacao", "aplicação", "rentabilidade"],
  },
  {
    title: "Cheque Especial",
    desc: "Acesso ao formulário de cheque especial.",
    href: "/auth/cheque_especial",
    group: "Financeiro",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CHEQUE_ESPECIAL],
    keywords: ["cheque especial", "limite", "credito", "crédito", "formulario"],
  },
  {
    title: "Declaração de Rendimentos",
    desc: "Emitir ou acessar declaração de rendimentos.",
    href: "/auth/declaracao_rendimentos",
    group: "Formulários de Cadastro",
    keywords: ["declaracao", "declaração", "rendimentos", "comprovante", "informe"],
  },
  {
    title: "Demissão",
    desc: "Acesso ao formulário de desligamento.",
    href: "/auth/demissao",
    group: "RH",
    keywords: ["demissao", "demissão", "desligamento", "rescisao", "rescisão"],
  },
  {
    title: "Ficha de Desimpedimento",
    desc: "Acesso ao formulário de ficha de desimpedimento.",
    href: "/auth/ficha_desimpedimento",
    group: "Formulários de Cadastro",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["desimpedimento", "ficha", "formulario", "formulário", "cadastro"],
  },

  {
    title: "Despesas/Viagens - Solicitação",
    desc: "Solicitar reembolso de despesas e viagens.",
    href: "/auth/cadastro_reembolso_despesa",
    group: "Financeiro",
    pinned: true,
    keywords: ["reembolso", "despesas", "viagem", "prestacao", "prestação", "solicitacao", "solicitação"],
  },
  {
    title: "Despesas/Viagens - Gerenciamento",
    desc: "Gerenciar solicitações de reembolso de despesas e viagens.",
    href: "/auth/gerenciamento_reembolso_despesa",
    group: "Financeiro",
    keywords: ["reembolso", "despesas", "viagem", "gerenciamento", "consulta"],
  },

  {
    title: "Docusign",
    desc: "Consultar e gerenciar documentos via DocuSign.",
    href: "/auth/docusign",
    group: "Documentos",
    pinned: true,
    allowedGroups: [GROUPS.SUPORTE, GROUPS.DOCUSIGN],
    keywords: ["docusign", "assinatura", "documento", "pdf", "envelope"],
  },
  {
    title: "Empréstimo Consignado",
    desc: "Acesso ao formulário de empréstimo consignado.",
    href: "/auth/emprestimo_consignado",
    group: "Crédito",
    keywords: ["emprestimo", "empréstimo", "consignado", "credito", "crédito"],
  },

  {
    title: "Alteração de Capital",
    desc: "Acesso ao formulário de alteração de capital.",
    href: "/auth/alteracao_capital",
    group: "Formulários de Cadastro",
    keywords: ["capital", "alteracao", "alteração", "formulario", "cadastro"],
  },
  {
    title: "Declaração de Residência",
    desc: "Acesso ao formulário de declaração de residência.",
    href: "/auth/declaracao_residencia",
    group: "Formulários de Cadastro",
    keywords: ["declaracao", "declaração", "residencia", "residência", "comprovante"],
  },
  {
    title: "Procuração Ortugante PF/PJ",
    desc: "Acesso ao formulário de procuração outorgante PF/PJ.",
    href: "/auth/procuracao_ortugante",
    group: "Formulários de Cadastro",
    keywords: ["procuracao", "procuração", "outorgante", "ortugante", "pf", "pj"],
  },
  {
    title: "Renúncia de Procurador",
    desc: "Acesso ao formulário de renúncia de procurador.",
    href: "/auth/renuncia_procurador",
    group: "Formulários de Cadastro",
    keywords: ["renuncia", "renúncia", "procurador", "formulario", "cadastro"],
  },
  {
    title: "Tabela de Integralização",
    desc: "Consultar tabela de integralização.",
    href: "/auth/tabela_integralizacao",
    group: "Formulários de Cadastro",
    keywords: ["tabela", "integralizacao", "integralização", "capital", "cadastro"],
  },

  {
    title: "Adendo Contratual",
    desc: "Acesso ao formulário de adendo contratual.",
    href: "/auth/adendo_contratual",
    group: "Formulários de Empréstimos",
    keywords: ["adendo", "contratual", "contrato", "emprestimo", "empréstimo"],
  },
  {
    title: "Adiantamento Salarial - Empréstimo",
    desc: "Acesso ao formulário de adiantamento salarial para empréstimos.",
    href: "/auth/adiantamento_salarial_emprestimo",
    group: "Formulários de Empréstimos",
    keywords: ["adiantamento", "salarial", "emprestimo", "empréstimo", "desconto"],
  },
  {
    title: "Autorização de Débito",
    desc: "Acesso ao formulário de autorização de débito.",
    href: "/auth/autorizacao_debito",
    group: "Formulários de Empréstimos",
    keywords: ["autorizacao", "autorização", "debito", "débito", "formulario"],
  },
  {
    title: "Cálculo de Margem",
    desc: "Acesso ao cálculo de margem consignável.",
    href: "/auth/margem_consignavel",
    group: "Formulários de Empréstimos",
    keywords: ["margem", "consignavel", "consignável", "calculo", "cálculo"],
  },
  {
    title: "Formulário DPS",
    desc: "Acesso ao formulário DPS.",
    href: "/auth/formulario_dps",
    group: "Formulários de Empréstimos",
    keywords: ["dps", "seguro", "formulario", "formulário"],
  },
  {
    title: "Formulário Previsul",
    desc: "Acesso ao formulário Previsul.",
    href: "/auth/previsul",
    group: "Formulários de Empréstimos",
    keywords: ["previsul", "seguro", "formulario", "formulário"],
  },
  {
    title: "Simulador de Desconto",
    desc: "Simular desconto em operações de empréstimo.",
    href: "/auth/simulador_desconto",
    group: "Formulários de Empréstimos",
    keywords: ["simulador", "desconto", "emprestimo", "empréstimo", "calculo"],
  },
  {
    title: "Termo de Garantia",
    desc: "Acesso ao termo de garantia.",
    href: "/auth/termo_garantia",
    group: "Formulários de Empréstimos",
    keywords: ["termo", "garantia", "emprestimo", "empréstimo", "contrato"],
  },

  {
    title: "Adiantamento Salarial",
    desc: "Acesso ao formulário de adiantamento salarial.",
    href: "/auth/adiantamento_salarial",
    group: "Formulários do RH",
    keywords: ["adiantamento", "salarial", "rh", "salario", "salário"],
  },
  {
    title: "Auxílio Creche",
    desc: "Acesso ao formulário de auxílio creche / babá.",
    href: "/auth/auxilio_creche",
    group: "Formulários do RH",
    keywords: ["auxilio", "auxílio", "creche", "baba", "babá", "rh"],
  },
  {
    title: "Bolsa de Estudo",
    desc: "Acesso ao formulário de bolsa de estudo.",
    href: "/auth/bolsa_estudo",
    group: "Formulários do RH",
    keywords: ["bolsa", "estudo", "rh", "educacao", "educação"],
  },
  {
    title: "Reembolso Convênio Médico",
    desc: "Acesso ao formulário de reembolso de convênio médico.",
    href: "/auth/reembolso_convenio_medico",
    group: "Formulários do RH",
    keywords: ["reembolso", "convenio", "convênio", "medico", "médico", "rh"],
  },

  {
    title: "Aplicar Marca d'Água",
    desc: "Adicionar marca d'água em arquivos.",
    href: "/auth/aplica_marca_dagua",
    group: "Ferramentas",
    keywords: ["marca d'agua", "marca dágua", "pdf", "arquivo", "documento"],
  },
  {
    title: "Conversor de Arquivos",
    desc: "Converter arquivos para diferentes formatos.",
    href: "/auth/conversor_arquivos",
    group: "Ferramentas",
    pinned: true,
    keywords: ["converter", "arquivo", "pdf", "documento", "formato"],
  },
  {
    title: "Juntar PDF",
    desc: "Juntar múltiplos PDFs em um único arquivo.",
    href: "/auth/juntar_pdf",
    group: "Ferramentas",
    keywords: ["juntar", "unir", "pdf", "arquivo"],
  },

  {
    title: "Cadastro de Contrato",
    desc: "Cadastrar contratos.",
    href: "/auth/cadastro_contrato",
    group: "Contratos",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CONTRATOS],
    keywords: ["contrato", "cadastro", "novo contrato"],
  },
  {
    title: "Consulta de Contratos",
    desc: "Consultar contratos cadastrados.",
    href: "/auth/consulta_contratos",
    group: "Contratos",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CONTRATOS],
    keywords: ["contrato", "consulta", "buscar contrato"],
  },

  {
    title: "Cadastro Convênio Odonto",
    desc: "Cadastrar convênios odontológicos.",
    href: "/auth/cadastro_convenio_odonto",
    group: "Benefícios",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["convenio", "convênio", "odonto", "cadastro", "plano"],
  },
  {
    title: "Gerenciamento Convênio Odonto",
    desc: "Consultar e gerenciar convênios odontológicos.",
    href: "/auth/gerenciamento_convenio_odonto",
    group: "Benefícios",
    keywords: ["convenio", "convênio", "odonto", "consulta", "gerenciamento"],
  },
  {
    title: "Gerenciamento Valor Convênio Odonto",
    desc: "Gerenciar valores de convênios odontológicos.",
    href: "/auth/gerenciamento_valor_convenio_odonto",
    group: "Benefícios",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["convenio", "convênio", "odonto", "valor", "preco", "preço"],
  },
  {
    title: "Relatório Convênio Odonto",
    desc: "Visualizar relatórios de convênios odontológicos.",
    href: "/auth/relatorio_convenio_odonto",
    group: "Benefícios",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["convenio", "convênio", "odonto", "relatorio", "relatório"],
  },

  {
    title: "Gerenciamento de Cargos",
    desc: "Gerenciar cargos cadastrados.",
    href: "/auth/gerenciamento_cargo",
    group: "Funcionários",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["cargo", "cargos", "funcionario", "funcionário", "rh"],
  },
  {
    title: "Gerenciamento de Funcionários",
    desc: "Consultar e administrar funcionários.",
    href: "/auth/gerenciamento_funcionario",
    group: "Funcionários",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["funcionario", "funcionário", "colaborador", "rh"],
  },
  {
    title: "Gerenciamento de Posições",
    desc: "Gerenciar posições cadastradas.",
    href: "/auth/gerenciamento_posicao",
    group: "Funcionários",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["posicao", "posição", "cargo", "funcionario"],
  },
  {
    title: "Gerenciamento de Setores",
    desc: "Gerenciar setores da empresa.",
    href: "/auth/gerenciamento_setor",
    group: "Funcionários",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["setor", "setores", "departamento", "funcionario"],
  },

  {
    title: "Cadastro de Férias",
    desc: "Cadastrar férias de funcionários.",
    href: "/auth/cadastro_ferias",
    group: "RH",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["ferias", "férias", "cadastro", "descanso"],
  },
  {
    title: "Gerenciamento de Férias",
    desc: "Consultar e gerenciar férias.",
    href: "/auth/gerenciamento_ferias",
    group: "RH",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.RH],
    keywords: ["ferias", "férias", "consulta", "gerenciamento"],
  },

  {
    title: "Cadastro de Notebook",
    desc: "Cadastrar notebooks.",
    href: "/auth/cadastro_notebook",
    group: "TI",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.TI],
    keywords: ["notebook", "equipamento", "cadastro", "ti"],
  },
  {
    title: "Consulta de Notebook",
    desc: "Consultar notebooks cadastrados.",
    href: "/auth/consulta_notebook",
    group: "TI",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.TI],
    keywords: ["notebook", "equipamento", "consulta", "ti"],
  },

  {
    title: "Solicitação de Participação",
    desc: "Solicitar participação em ações de marketing.",
    href: "/auth/solicitacao_participacao",
    group: "Marketing",
    keywords: ["marketing", "participacao", "participação", "solicitacao", "solicitação"],
  },
  {
    title: "Gerenciamento de Participação",
    desc: "Consultar participações de marketing.",
    href: "/auth/gerenciamento_participacao",
    group: "Marketing",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.MARKETING],
    keywords: ["marketing", "participacao", "participação", "consulta", "gerenciamento"],
  },

  {
    title: "Migração de Contrato",
    desc: "Migrar contratos no sistema.",
    href: "/auth/migracao_contrato",
    group: "Contratos",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.CADASTRO],
    keywords: ["migracao", "migração", "contrato", "importacao", "importação"],
  },

  {
    title: "GED no App",
    desc: "Acesso ao processo GED no aplicativo.",
    href: "/auth/assinatura_eletronica",
    group: "Processos GED",
    keywords: ["ged", "app", "assinatura", "eletronica", "eletrônica"],
  },
  {
    title: "Senha não correntista App",
    desc: "Acesso ao processo de senha para não correntista.",
    href: "/auth/senha_sicoobnet",
    group: "Processos GED",
    keywords: ["senha", "nao correntista", "não correntista", "app", "sicoobnet"],
  },

  {
    title: "Ramal",
    desc: "Consultar ramais internos.",
    href: "/auth/ramais",
    badge: "rápido",
    group: "Geral",
    pinned: true,
    keywords: ["telefone", "contato", "ramal", "setor", "lista telefonica", "lista telefônica"],
  },
  {
    title: "RCO",
    desc: "Acesso à tela de RCO.",
    href: "/auth/rco",
    group: "Ferramentas",
    keywords: ["rco", "credito", "crédito", "simulacao", "simulação"],
  },

  {
    title: "Cadastro Recibo Financeiro",
    desc: "Cadastrar recibos financeiros.",
    href: "/auth/cadastro_recibo_financeiro",
    group: "Financeiro",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.FINANCEIRO, GROUPS.COBRANCA],
    keywords: ["recibo", "financeiro", "cadastro", "pagamento"],
  },
  {
    title: "Consulta Recibo Financeiro",
    desc: "Consultar recibos financeiros.",
    href: "/auth/consulta_recibo_financeiro",
    group: "Financeiro",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.FINANCEIRO, GROUPS.COBRANCA],
    keywords: ["recibo", "financeiro", "consulta", "pagamento"],
  },

  {
    title: "Relação de Faturamento",
    desc: "Acesso ao relatório de faturamento.",
    href: "/auth/relacao_faturamento",
    group: "Financeiro",
    keywords: ["faturamento", "relatorio", "relatório", "mensal", "dados"],
  },
  {
    title: "Produção/Meta/PA",
    desc: "Consultar consolidado e metas por PA.",
    href: "/auth/producao_meta_cooperativa_pa",
    group: "Relatórios",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.GERENCIA_DIRETORIA],
    keywords: ["producao", "produção", "meta", "pa", "relatorio", "relatório"],
  },
  {
    title: "Produção/Meta/Macro",
    desc: "Consultar consolidado e metas por Macro.",
    href: "/auth/producao_meta_cooperativa_macro",
    group: "Relatórios",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.GERENCIA_DIRETORIA],
    keywords: ["producao", "produção", "meta", "macro", "relatorio", "relatório"],
  },

  {
    title: "Reset de Senha E-mail",
    desc: "Abrir o sistema externo para redefinição de senha do e-mail.",
    href: "https://sistemas.sisbr.coop.br/mtse/login",
    group: "Geral",
    pinned: true,
    keywords: ["reset", "senha", "email", "e-mail", "sicoob", "externo"],
  },

  {
    title: "Resgate Capital",
    desc: "Acesso ao formulário de resgate de capital.",
    href: "/auth/resgate_capital",
    group: "Financeiro",
    keywords: ["resgate", "capital", "formulario", "financeiro"],
  },
  {
    title: "Termo de Responsabilidade TI",
    desc: "Acesso ao termo de responsabilidade de uso.",
    href: "/auth/termo_responsabilidade_uso",
    group: "TI",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.TI],
    keywords: ["termo", "responsabilidade", "ti", "uso", "equipamento"],
  },
  {
    title: "Tabela Sisbr TI",
    desc: "Consultar informações técnicas da tabela Sisbr TI.",
    href: "/auth/tabela_sisbr_ti",
    group: "TI",
    allowedGroups: [GROUPS.SUPORTE, GROUPS.TI],
    keywords: ["sisbr", "ti", "tabela", "dados", "rede"],
  },
];