import { ScreenItem } from "@/components/search-home/search-home";

export const SCREENS: ScreenItem[] = [
  {
    title: "Ramal",
    desc: "Consultar ramais internos.",
    href: "/auth/ramais",
    badge: "rápido",
    group: "Geral",
    pinned: true,
    keywords: ["telefone", "contato", "ramal", "setor"],
  },
  {
    title: "Aniversariantes",
    desc: "Ver aniversariantes do dia.",
    href: "/auth/aniversariantes",
    group: "RH",
    pinned: true,
    keywords: ["rh", "datas", "aniversario"],
  },
  {
    title: "Despesas/Viagens",
    desc: "Solicitar ou gerenciar reembolsos.",
    href: "/auth/cadastro_reembolso_despesa",
    group: "Financeiro",
    pinned: true,
    keywords: ["reembolso", "despesas", "viagem", "prestacao"],
  },
  {
    title: "Gerenciador de Arquivos",
    desc: "Marca d’água, converter e juntar PDF.",
    href: "/auth/conversor_arquivos",
    group: "Ferramentas",
    pinned: true,
    keywords: ["pdf", "converter", "juntar", "arquivo", "watermark"],
  },
  {
    title: "Convênios",
    desc: "Consulta e gerenciamento.",
    href: "/auth/gerenciamento_convenio_odonto",
    group: "Benefícios",
    keywords: ["odonto", "convenio", "plano"],
  },
  {
    title: "Relação de Faturamento",
    desc: "Acesso ao relatório.",
    href: "/auth/relacao_faturamento",
    group: "Financeiro",
    keywords: ["faturamento", "relatorio", "mensal"],
  },
  {
    title: "Alteração de Capital",
    desc: "Acesso ao formulário.",
    href: "/auth/alteracao_capital",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Tabela de Integralização",
    desc: "Acesso ao formulário.",
    href: "/auth/tabela_integralizacao",
    group: "Informe de integralização",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Adiantamento Salarial",
    desc: "Acesso ao formulário.",
    href: "/auth/adiantamento_salarial",
    group: "Formulários do RH",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Auxílio Creche",
    desc: "Acesso ao formulário.",
    href: "/auth/auxilio_creche",
    group: "Formulários do RH",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Declaração de Rendimentos",
    desc: "Acesso ao formulário.",
    href: "/auth/declaracao_rendimentos",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Docusign",
    desc: "Acesso ao formulário.",
    href: "/auth/docusign",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Empréstimo Consignado",
    desc: "Acesso ao formulário.",
    href: "/auth/emprestimo_consignado",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Ficha de Desimpedimento",
    desc: "Acesso ao formulário.",
    href: "/auth/ficha_desimpedimento",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Procuração Ortugante",
    desc: "Acesso ao formulário.",
    href: "/auth/procuracao_ortugante",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Renuncia Procurador",
    desc: "Acesso ao formulário.",
    href: "/auth/renuncia_procurador",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Simulador de Investimento",
    desc: "Acesso ao formulário.",
    href: "/auth/simulador_investimento",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Ficha de Desimpedimento",
    desc: "Acesso ao formulário.",
    href: "/auth/ficha_desimpedimento",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Tabela de Integralização",
    desc: "Acesso ao formulário.",
    href: "/auth/tabela_integralizacao",
    group: "Formulários de Cadastro",
    keywords: ["faturamento", "relatorio", "formulario"],
  },
  {
    title: "Calculadora de Juros Cartão",
    desc: "Acesso ao formulário.",
    href: "/auth/calculadora_juros_cartao",
    group: "Ferramentas",
    keywords: ["calculadora", "juros", "cartao", "cartão"],
  },
  {
    title: "Simulação de Crédito Consignado",
    desc: "Acesso ao formulário.",
    href: "/auth/rco",
    group: "Ferramentas",
    keywords: ["calculadora", "rco"],
  },

];