export type TemaFuncionario =
  | "consorcio"
  | "seguro_gerais_novo"
  | "entrada_cooperados"
  | "conta_corrente_abertas"
  | "seguro_venda_nova"
  | "seguro_rural"
  | "saldo_previdencia_mi"
  | "saldo_previdencia_vgbl";

export function getSql(tema: TemaFuncionario) {
  switch (tema) {
    case "consorcio":
      return sqlConsorcio();
    case "seguro_gerais_novo":
      return sqlSeguroGeraisNovo();
    case "entrada_cooperados":
      return sqlEntradaCooperados();
    case "conta_corrente_abertas":
      return sqlContaCorrenteAbertas();
    case "seguro_venda_nova":
      return sqlSeguroVendaNova();
    case "seguro_rural":
      return sqlSeguroRural();
    case "saldo_previdencia_mi":
      return sqlSaldoPrevidenciaMi();
    case "saldo_previdencia_vgbl":
      return sqlSaldoPrevidenciaVgbl();
    default:
      throw new Error("Tema não suportado.");
  }
}

function sqlConsorcio() {
  return `
    WITH
      PARAMS AS (
        SELECT
          TO_DATE(:dt_inicio,'DD/MM/YYYY') AS DT_INI_SEMANA,
          TO_DATE(:dt_fim,'DD/MM/YYYY')    AS DT_FIM_SEMANA
        FROM DUAL
      ),
      VENDEDORES_95 AS (
        SELECT 'YASMIN DE QUEIROZ LEMOS RIBEIRO' AS NM FROM DUAL UNION ALL
        SELECT 'CHRISTIAN JESUS SIQUEIRA' FROM DUAL UNION ALL
        SELECT 'GUSTAVO COLAFRANCESCO AMIM SOARES' FROM DUAL UNION ALL
        SELECT 'THIAGO SILVERIO DOS REIS' FROM DUAL
      ),
      PERIODO_REF AS (
        SELECT NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF FROM PARAMS
      ),
      CDN_BASE_ALL AS (
        SELECT
          NR_PA,
          TRUNC(
            CASE
              WHEN REGEXP_LIKE(TRIM(DT_ADESAO), '^\\d{2}/\\d{2}/\\d{4}$')
                THEN TO_DATE(TRIM(DT_ADESAO), 'DD/MM/YYYY')
              WHEN REGEXP_LIKE(TRIM(DT_ADESAO), '^\\d{4}-\\d{2}-\\d{2}$')
                THEN TO_DATE(TRIM(DT_ADESAO), 'YYYY-MM-DD')
            END
          ) AS DT_MOV,
          NVL(VL_CONTRATADO,0) AS VL_CONTRATADO_NUM,
          SN_VENDA_CONCLUIDA,
          SITUACAO_COTA,
          DESC_VERSAO_COTA,
          NR_COOPERATIVA,
          UPPER(TRIM(NM_VENDEDOR)) AS NM_VENDEDOR
        FROM DBACRESSEM.CONSORCIO_MENSAL_NOVO
        WHERE DT_ADESAO IS NOT NULL
        UNION ALL
        SELECT
          4317 AS NR_PA,
          TRUNC(
            CASE
              WHEN REGEXP_LIKE(TRIM(DT_ADESAO), '^\\d{2}/\\d{2}/\\d{4}$')
                THEN TO_DATE(TRIM(DT_ADESAO), 'DD/MM/YYYY')
              WHEN REGEXP_LIKE(TRIM(DT_ADESAO), '^\\d{4}-\\d{2}-\\d{2}$')
                THEN TO_DATE(TRIM(DT_ADESAO), 'YYYY-MM-DD')
            END
          ) AS DT_MOV,
          NVL(VL_CONTRATADO,0) AS VL_CONTRATADO_NUM,
          SN_VENDA_CONCLUIDA,
          SITUACAO_COTA,
          DESC_VERSAO_COTA,
          NR_COOPERATIVA,
          UPPER(TRIM(NM_VENDEDOR)) AS NM_VENDEDOR
        FROM DBACRESSEM.CONSORCIO_MENSAL_NOVO
        WHERE DT_ADESAO IS NOT NULL
          AND REGEXP_LIKE(TRIM(NR_COOPERATIVA), '^\\d+$')
          AND TO_NUMBER(TRIM(NR_COOPERATIVA)) = 4317
      ),
      CDN_BASE_AJUSTADA AS (
        SELECT
          CASE
            WHEN B.NR_PA = 0
             AND EXISTS (
               SELECT 1
               FROM VENDEDORES_95 V
               WHERE UPPER(TRIM(V.NM)) = B.NM_VENDEDOR
             )
            THEN 95
            ELSE B.NR_PA
          END AS NR_PA_EFETIVO,
          B.DT_MOV,
          B.VL_CONTRATADO_NUM,
          B.SN_VENDA_CONCLUIDA,
          B.SITUACAO_COTA,
          B.DESC_VERSAO_COTA,
          B.NR_COOPERATIVA,
          B.NM_VENDEDOR AS NM_FUNCIONARIO
        FROM CDN_BASE_ALL B
      ),
      CDN_BASE AS (
        SELECT B.*
        FROM CDN_BASE_AJUSTADA B
        CROSS JOIN PARAMS PR
        WHERE
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          OR
          (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                       AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
      ),
      FUNCIONARIO_PA AS (
        SELECT
          X.NM_FUNCIONARIO,
          X.NR_PA
        FROM (
          SELECT
            B.NM_VENDEDOR AS NM_FUNCIONARIO,
            CASE
              WHEN B.NR_PA = 0
               AND EXISTS (
                 SELECT 1
                 FROM VENDEDORES_95 V
                 WHERE UPPER(TRIM(V.NM)) = B.NM_VENDEDOR
               )
              THEN 95
              ELSE B.NR_PA
            END AS NR_PA,
            ROW_NUMBER() OVER (
              PARTITION BY B.NM_VENDEDOR
              ORDER BY B.DT_MOV DESC
            ) AS RN
          FROM CDN_BASE_ALL B
          WHERE B.NM_VENDEDOR IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      CONS_ANO AS (
        SELECT
          B.NR_PA_EFETIVO AS NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          SUM(B.VL_CONTRATADO_NUM) AS PRODUCAO_ANO
        FROM CDN_BASE_AJUSTADA B
        CROSS JOIN PARAMS PR
        WHERE EXTRACT(YEAR FROM B.DT_MOV) = EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
          AND B.SN_VENDA_CONCLUIDA = 'SIM'
          AND B.SITUACAO_COTA <> 'EXCLUIDO'
          AND B.DESC_VERSAO_COTA = 'ATIVA'
        GROUP BY
          B.NR_PA_EFETIVO,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      CONS_MES AS (
        SELECT
          B.NR_PA_EFETIVO AS NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)  AS ANO,
          EXTRACT(MONTH FROM B.DT_MOV) AS MES,
          SUM(B.VL_CONTRATADO_NUM) AS PRODUCAO_MES
        FROM CDN_BASE B
        WHERE B.SN_VENDA_CONCLUIDA = 'SIM'
          AND B.SITUACAO_COTA <> 'EXCLUIDO'
          AND B.DESC_VERSAO_COTA = 'ATIVA'
        GROUP BY
          B.NR_PA_EFETIVO,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV),
          EXTRACT(MONTH FROM B.DT_MOV)
      ),
      CONS_SEMANAL AS (
        SELECT
          B.NR_PA_EFETIVO AS NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          SUM(B.VL_CONTRATADO_NUM) AS PRODUCAO_SEMANAL
        FROM CDN_BASE B
        CROSS JOIN PARAMS PR
        WHERE B.SN_VENDA_CONCLUIDA = 'SIM'
          AND B.SITUACAO_COTA <> 'EXCLUIDO'
          AND B.DESC_VERSAO_COTA = 'ATIVA'
        GROUP BY
          B.NR_PA_EFETIVO,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      META_ANO AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          SUM(NVL(MF.QTD_META, 0)) AS META_ANO
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 3
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META)
      ),
      META_MES AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          EXTRACT(MONTH FROM MF.DT_META) AS MES,
          SUM(NVL(MF.QTD_META, 0)) AS META_MES
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 3
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META),
          EXTRACT(MONTH FROM MF.DT_META)
      ),
      BASE_FUNCIONARIOS AS (
        SELECT
          NVL(FP.NR_PA, 0) AS NR_PA,
          MA.NM_FUNCIONARIO,
          MA.ANO
        FROM META_ANO MA
        LEFT JOIN FUNCIONARIO_PA FP
          ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
      )
    SELECT
      BF.NM_FUNCIONARIO,
      TO_CHAR(NVL(SW.PRODUCAO_SEMANAL, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_SEMANAL,
      TO_CHAR(
        ROUND(NVL(MA.META_ANO, 0) / 52, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(MA.META_ANO, 0) / 52, 0) > 0
          THEN ROUND((NVL(SW.PRODUCAO_SEMANAL,0) / ROUND(NVL(MA.META_ANO, 0) / 52, 0)) * 100, 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      TO_CHAR(
        NVL(SW.PRODUCAO_SEMANAL,0) - ROUND(NVL(MA.META_ANO, 0) / 52, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS GAP_SEMANAL,
      TO_CHAR(NVL(AY.PRODUCAO_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_ANO,
      TO_CHAR(NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_2026,
      CASE
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO,0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      TO_CHAR((NVL(AY.PRODUCAO_ANO,0) - NVL(MA.META_ANO,0)),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    LEFT JOIN DBACRESSEM.PA P
      ON P.NR_PA = BF.NR_PA
    CROSS JOIN PARAMS PR
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    AND MA.ANO = BF.ANO
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    AND MM.ANO = BF.ANO
    AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN CONS_ANO AY
      ON AY.NR_PA = BF.NR_PA
    AND AY.ANO = BF.ANO
    AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN CONS_MES MJ
      ON MJ.NR_PA = BF.NR_PA
    AND MJ.ANO = BF.ANO
    AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
    AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN CONS_SEMANAL SW
      ON SW.NR_PA = BF.NR_PA
    AND SW.ANO = BF.ANO
    AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlSeguroGeraisNovo() {
  return `
    WITH
    PARAMS AS (
      SELECT
        TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
        TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA  
      FROM DUAL
    ),
    ANGARIADORES_95 AS (
      SELECT 'YASMIN QUEIROS LEMOS RIBEIRO' AS NM FROM DUAL UNION ALL
      SELECT 'CHRISTIAN JESUS SIQUEIRA' FROM DUAL UNION ALL
      SELECT 'THIAGO SILVERIO DOS REIS' FROM DUAL UNION ALL
      SELECT 'THIAGO SILV�RIO DOS REIS' FROM DUAL UNION ALL
      SELECT 'GUSTAVO COLAFRANCESCO AMIM SOARES' FROM DUAL
    ),
    PERIODO_REF AS (
      SELECT
        NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF
      FROM PARAMS
    ),
    SGPD_BASE_ALL AS (
      SELECT
        CASE
          WHEN REGEXP_LIKE(TRIM(NR_COOPERATIVA),'^[0-9]+$')
           AND TO_NUMBER(TRIM(NR_COOPERATIVA)) = 4317
          THEN 4317
          ELSE NR_PA
        END AS NR_PA,
        TO_DATE(DT_MOVIMENTO,'DD/MM/YYYY') AS DT_MOV,
        NVL(VL_PREMIO_LIQUIDO,0) AS VL_PREMIO_LIQUIDO_NUM,
        UPPER(TRIM(NR_CPF_CNPJ_ANGARIADOR)) AS NM_FUNCIONARIO
      FROM DBACRESSEM.SEGUROS_GERAIS_PRODUCAO_DIARIO
      WHERE DT_MOVIMENTO IS NOT NULL
        AND UPPER(DESC_TP_PROPOSTA) = 'SEGURO NOVO'
    ),
    SGPD_BASE_AJUSTADA AS (
      SELECT
        CASE
          WHEN B.NR_PA = 0
           AND EXISTS (
             SELECT 1
             FROM ANGARIADORES_95 A
             WHERE UPPER(TRIM(A.NM)) = B.NM_FUNCIONARIO
           )
          THEN 95
          ELSE B.NR_PA
        END AS NR_PA_EFETIVO,
        B.DT_MOV,
        B.VL_PREMIO_LIQUIDO_NUM,
        B.NM_FUNCIONARIO
      FROM SGPD_BASE_ALL B
    ),
    SGPD_BASE AS (
      SELECT
        B.*
      FROM SGPD_BASE_AJUSTADA B
      CROSS JOIN PARAMS PR
      WHERE
        (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
        OR
        (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                     AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
    ),
    FUNCIONARIO_PA AS (
      SELECT
        X.NM_FUNCIONARIO,
        X.NR_PA
      FROM (
        SELECT
          B.NM_FUNCIONARIO,
          CASE
            WHEN B.NR_PA = 0
             AND EXISTS (
               SELECT 1
               FROM ANGARIADORES_95 A
               WHERE UPPER(TRIM(A.NM)) = B.NM_FUNCIONARIO
             )
            THEN 95
            ELSE B.NR_PA
          END AS NR_PA,
          ROW_NUMBER() OVER (
            PARTITION BY B.NM_FUNCIONARIO
            ORDER BY B.DT_MOV DESC
          ) AS RN
        FROM SGPD_BASE_ALL B
        WHERE B.NM_FUNCIONARIO IS NOT NULL
      ) X
      WHERE X.RN = 1
    ),
    SGPD_ANO AS (
      SELECT
        B.NR_PA_EFETIVO AS NR_PA,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
        SUM(B.VL_PREMIO_LIQUIDO_NUM) AS PRODUCAO_ANO
      FROM SGPD_BASE_AJUSTADA B
      CROSS JOIN PARAMS PR
      WHERE B.DT_MOV BETWEEN TRUNC(NVL(PR.DT_FIM_SEMANA, SYSDATE), 'YYYY')
                         AND NVL(PR.DT_FIM_SEMANA, SYSDATE)
      GROUP BY
        B.NR_PA_EFETIVO,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV)
    ),
    SGPD_MES AS (
      SELECT
        B.NR_PA_EFETIVO AS NR_PA,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
        EXTRACT(MONTH FROM B.DT_MOV) AS MES,
        SUM(B.VL_PREMIO_LIQUIDO_NUM) AS PRODUCAO_MES
      FROM SGPD_BASE B
      GROUP BY
        B.NR_PA_EFETIVO,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV),
        EXTRACT(MONTH FROM B.DT_MOV)
    ),
    SGPD_SEMANAL AS (
      SELECT
        B.NR_PA_EFETIVO AS NR_PA,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
        SUM(B.VL_PREMIO_LIQUIDO_NUM) AS PRODUCAO_SEMANAL
      FROM SGPD_BASE B
      CROSS JOIN PARAMS PR
      WHERE
        (
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          AND B.DT_MOV BETWEEN TRUNC(SYSDATE,'IW') AND (TRUNC(SYSDATE,'IW') + 6)
        )
        OR
        (
          (PR.DT_INI_SEMANA IS NOT NULL OR PR.DT_FIM_SEMANA IS NOT NULL)
          AND B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                          AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31')
        )
      GROUP BY
        B.NR_PA_EFETIVO,
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV)
    ),
    META_ANO AS (
      SELECT
        UPPER(TRIM(MF.NR_CPF_CNPJ)) AS NM_FUNCIONARIO,
        MAX(MF.NM_FUNCIONARIO) AS NM_FUNCIONARIO_NOME,
        EXTRACT(YEAR FROM MF.DT_META) AS ANO,
        SUM(NVL(MF.QTD_META, 0)) AS META_ANO
      FROM DBACRESSEM.META_FUNCIONARIOS MF
      WHERE MF.CD_PRODUTO = 27
      GROUP BY
        UPPER(TRIM(MF.NR_CPF_CNPJ)),
        EXTRACT(YEAR FROM MF.DT_META)
    ),
    META_MES AS (
      SELECT
        UPPER(TRIM(MF.NR_CPF_CNPJ)) AS NM_FUNCIONARIO,
        EXTRACT(YEAR FROM MF.DT_META) AS ANO,
        EXTRACT(MONTH FROM MF.DT_META) AS MES,
        SUM(NVL(MF.QTD_META, 0)) AS META_MES
      FROM DBACRESSEM.META_FUNCIONARIOS MF
      WHERE MF.CD_PRODUTO = 27
      GROUP BY
        UPPER(TRIM(MF.NR_CPF_CNPJ)),
        EXTRACT(YEAR FROM MF.DT_META),
        EXTRACT(MONTH FROM MF.DT_META)
    ),
    SEMANAS_MES AS (
      SELECT
        ANO,
        MES,
        COUNT(DISTINCT SEMANA) AS QTD_SEMANAS_MES
      FROM (
        SELECT
          EXTRACT(YEAR FROM DT_DIA) AS ANO,
          EXTRACT(MONTH FROM DT_DIA) AS MES,
          TO_NUMBER(TO_CHAR(DT_DIA, 'IW')) AS SEMANA
        FROM (
          SELECT
            ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1) AS DT_DIA
          FROM (
            SELECT LEVEL AS NIVEL_MES FROM DUAL CONNECT BY LEVEL <= 36
          ),
          (
            SELECT LEVEL AS NIVEL_DIA FROM DUAL CONNECT BY LEVEL <= 31
          )
          WHERE ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1)
                <= LAST_DAY(ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1))
        )
      )
      GROUP BY ANO, MES
    ),
    BASE_FUNCIONARIOS AS (
      SELECT
        NVL(FP.NR_PA, 0) AS NR_PA,
        MA.NM_FUNCIONARIO,
        MA.ANO
      FROM META_ANO MA
      LEFT JOIN FUNCIONARIO_PA FP
        ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
    )
    SELECT
      MA.NM_FUNCIONARIO_NOME AS NM_FUNCIONARIO,
      BF.NM_FUNCIONARIO AS CPF_FUNCIONARIO,
      BF.ANO,
      TO_CHAR(NVL(SW.PRODUCAO_SEMANAL, 0),
        'FML999G999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_SEMANAL,
      TO_CHAR(
        NVL(
          ROUND(
            NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
          , 2)
        , 0),
        'FML999G999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL_MES,
      TO_CHAR(
        ROUND(NVL(MA.META_ANO, 0) / 52, 2),
        'FML999G999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(MA.META_ANO, 0) / 52, 2) > 0 THEN
          ROUND(
            (NVL(SW.PRODUCAO_SEMANAL, 0) / ROUND(NVL(MA.META_ANO, 0) / 52, 2)) * 100
          , 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      TO_CHAR(
        NVL(SW.PRODUCAO_SEMANAL, 0)
        - ROUND(NVL(MA.META_ANO, 0) / 52, 2),
        'FML999G999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS GAP_SEMANAL,
      TO_CHAR(
        CASE
          WHEN BF.NR_PA = 95 THEN
            NVL(AY95.PRODUCAO_ANO, 0)
          WHEN BF.NR_PA = 0 THEN
            NVL(AY.PRODUCAO_ANO, 0) - NVL(AY95.PRODUCAO_ANO, 0)
          ELSE NVL(AY.PRODUCAO_ANO, 0)
        END,
        'FML999G999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_ANO,
      TO_CHAR(NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_2026,
      CASE
        WHEN NVL(MA.META_ANO, 0) > 0 THEN
          ROUND(
            (
              CASE
                WHEN BF.NR_PA = 95 THEN NVL(AY95.PRODUCAO_ANO, 0)
                WHEN BF.NR_PA = 0 THEN NVL(AY.PRODUCAO_ANO, 0) - NVL(AY95.PRODUCAO_ANO, 0)
                ELSE NVL(AY.PRODUCAO_ANO, 0)
              END
            ) / MA.META_ANO * 100
          , 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      TO_CHAR(
        (
          CASE
            WHEN BF.NR_PA = 95 THEN NVL(AY95.PRODUCAO_ANO, 0)
            WHEN BF.NR_PA = 0 THEN NVL(AY.PRODUCAO_ANO, 0) - NVL(AY95.PRODUCAO_ANO, 0)
            ELSE NVL(AY.PRODUCAO_ANO, 0)
          END
        ) - NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    CROSS JOIN PARAMS PR
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MA.ANO = BF.ANO
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MM.ANO = BF.ANO
     AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SEMANAS_MES SM
      ON SM.ANO = BF.ANO
     AND SM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SGPD_ANO AY
      ON AY.NR_PA = BF.NR_PA
     AND AY.ANO = BF.ANO
     AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SGPD_ANO AY95
      ON AY95.NR_PA = 95
     AND AY95.ANO = BF.ANO
     AND AY95.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SGPD_MES MJ
      ON MJ.NR_PA = BF.NR_PA
     AND MJ.ANO = BF.ANO
     AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
     AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SGPD_SEMANAL SW
      ON SW.NR_PA = BF.NR_PA
     AND SW.ANO = BF.ANO
     AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlEntradaCooperados() {
  return `
    WITH
      PARAMS AS (
        SELECT
          TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
          TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA
        FROM DUAL
      ),
      FUNC_LOGIN AS (
        SELECT
          X.NM_LOGIN,
          X.NM_FUNCIONARIO
        FROM (
          SELECT
            UPPER(TRIM(F.NM_LOGIN)) AS NM_LOGIN,
            UPPER(TRIM(F.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
            ROW_NUMBER() OVER (
              PARTITION BY UPPER(TRIM(F.NM_LOGIN))
              ORDER BY UPPER(TRIM(F.NM_FUNCIONARIO))
            ) AS RN
          FROM DBACRESSEM.FUNCIONARIOS_LOGIN F
          WHERE F.NM_LOGIN IS NOT NULL
            AND F.NM_FUNCIONARIO IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      FUNC_CAPITAL AS (
        SELECT
          FC.NR_CONTA_CAPITAL,
          UPPER(TRIM(FC.NM_USUARIO)) AS NM_USUARIO
        FROM DBACRESSEM.FUNCIONARIOS_CAPITAL FC
        WHERE FC.NR_CONTA_CAPITAL IS NOT NULL
          AND FC.NM_USUARIO IS NOT NULL
      ),
      AA_BASE_ALL AS (
        SELECT
          AA.NR_PA,
          TRUNC(AA.DT_MATRICULA) AS DT_MOV,
          AA.NR_CONTA_CAPITAL,
          FL.NM_FUNCIONARIO
        FROM DBACRESSEM.CONTA_CAPITAL_DIARIO_NOVO_NORMALIZADO AA
        LEFT JOIN DBACRESSEM.FUNCIONARIOS_CAPITAL FC
          ON FC.NR_CONTA_CAPITAL = AA.NR_CONTA_CAPITAL
        LEFT JOIN FUNC_LOGIN FL
          ON UPPER(TRIM(FC.NM_USUARIO)) = FL.NM_LOGIN
        WHERE AA.DT_MATRICULA IS NOT NULL
          AND AA.NR_CONTA_CAPITAL IS NOT NULL
          AND AA.SN_CONTA_CAPITAL = 'ATIVO'
          AND FC.CD_DOCUMENTO = 'INC.C.'
          AND FL.NM_FUNCIONARIO IS NOT NULL
        UNION ALL
        SELECT
          4317 AS NR_PA,
          TRUNC(AA.DT_MATRICULA) AS DT_MOV,
          AA.NR_CONTA_CAPITAL,
          FL.NM_FUNCIONARIO
        FROM DBACRESSEM.CONTA_CAPITAL_DIARIO_NOVO_NORMALIZADO AA
        LEFT JOIN DBACRESSEM.FUNCIONARIOS_CAPITAL FC
          ON FC.NR_CONTA_CAPITAL = AA.NR_CONTA_CAPITAL
        LEFT JOIN FUNC_LOGIN FL
          ON UPPER(TRIM(FC.NM_USUARIO)) = FL.NM_LOGIN
        WHERE AA.DT_MATRICULA IS NOT NULL
          AND AA.NR_CONTA_CAPITAL IS NOT NULL
          AND AA.SN_CONTA_CAPITAL = 'ATIVO'
          AND FC.CD_DOCUMENTO = 'INC.C.'
          AND REGEXP_LIKE(TRIM(AA.NR_COOPERATIVA), '^[0-9]+$')
          AND TO_NUMBER(TRIM(AA.NR_COOPERATIVA)) = 4317
          AND FL.NM_FUNCIONARIO IS NOT NULL
      ),
      AA_BASE AS (
        SELECT
          B.*
        FROM AA_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          OR
          (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                       AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
      ),
      FUNCIONARIO_PA AS (
        SELECT
          X.NM_FUNCIONARIO,
          X.NR_PA
        FROM (
          SELECT
            B.NM_FUNCIONARIO,
            B.NR_PA,
            ROW_NUMBER() OVER (
              PARTITION BY B.NM_FUNCIONARIO
              ORDER BY B.DT_MOV DESC
            ) AS RN
          FROM AA_BASE_ALL B
          WHERE B.NM_FUNCIONARIO IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      AA_ANO AS (
        SELECT
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          COUNT(DISTINCT B.NR_CONTA_CAPITAL) AS PRODUCAO_ANO
        FROM AA_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE EXTRACT(YEAR FROM B.DT_MOV) = EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
        GROUP BY
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      AA_SEMANAL AS (
        SELECT
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          COUNT(DISTINCT B.NR_CONTA_CAPITAL) AS PRODUCAO_SEMANAL
        FROM AA_BASE B
        CROSS JOIN PARAMS PR
        WHERE
          (
            (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
            AND B.DT_MOV BETWEEN TRUNC(SYSDATE,'IW') AND (TRUNC(SYSDATE,'IW') + 6)
          )
          OR
          (
            (PR.DT_INI_SEMANA IS NOT NULL OR PR.DT_FIM_SEMANA IS NOT NULL)
            AND B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                            AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31')
          )
        GROUP BY
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      META_ANO AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          SUM(NVL(MF.QTD_META, 0)) AS META_ANO
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 4
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META)
      ),
      BASE_FUNCIONARIOS AS (
        SELECT
          NVL(FP.NR_PA, 0) AS NR_PA,
          MA.NM_FUNCIONARIO,
          MA.ANO
        FROM META_ANO MA
        LEFT JOIN FUNCIONARIO_PA FP
          ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
      )
    SELECT
      BF.NM_FUNCIONARIO,
      BF.ANO,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        ELSE NVL(SW.PRODUCAO_SEMANAL, 0)
      END AS PRODUCAO_SEMANAL,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        ELSE NVL(AY.PRODUCAO_ANO, 0) - NVL(MA.META_ANO, 0)
      END AS FALTA_PARA_META,
      ROUND(NVL(MA.META_ANO, 0) / 52, 0) AS META_SEMANAL,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(SW.PRODUCAO_SEMANAL, 0) / ROUND(NVL(MA.META_ANO, 0) / 52, 0)) * 100, 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANAL,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        ELSE NVL(SW.PRODUCAO_SEMANAL, 0) - ROUND(NVL(MA.META_ANO, 0) / 52, 0)
      END AS GAP_SEMANAL,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        ELSE NVL(AY.PRODUCAO_ANO, 0)
      END AS PRODUCAO_ANO,
      NVL(MA.META_ANO, 0) AS META_2026,
      CASE
        WHEN BF.NR_PA = 95 THEN 0
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO, 0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA
    FROM BASE_FUNCIONARIOS BF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MA.ANO = BF.ANO
    LEFT JOIN AA_ANO AY
      ON AY.ANO = BF.ANO
     AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN AA_SEMANAL SW
      ON SW.ANO = BF.ANO
     AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlContaCorrenteAbertas() {
  return `
    WITH
    PARAMS AS (
      SELECT
        TO_DATE(:dt_inicio,'DD/MM/YYYY') AS DT_INI,
        TO_DATE(:dt_fim,'DD/MM/YYYY') AS DT_FIM
      FROM DUAL
    ),
    ANO_REF AS (
      SELECT EXTRACT(YEAR FROM DT_FIM) AS ANO
      FROM PARAMS
    ),
    BASE_CC AS (
      SELECT
        TRUNC(C.DT_ABERTURA_CONTA) AS DT_MOV,
        TRIM(C.NR_CPF_RESPONSAVEL_CADASTRO) AS CPF,
        C.NR_CONTA_CORRENTE
      FROM DBACRESSEM.CONTA_CORRENTE_DIARIO_NOVO_NORMALIZADO C
      WHERE C.DT_ABERTURA_CONTA IS NOT NULL
        AND C.NM_MODALIDADE_CONTA = 'CONTA CORRENTE'
        AND C.TP_CONTA_CORRENTE IN ('PESSOAS FÍSICAS','PESSOAS JURÍDICAS')
        AND C.NM_SITUACAO_CONTA_CORRENTE IN
            ('ATIVA','ATIVA BLOQUEADA','ATIVA BLOQUEADA JUDICIALMENTE')
        AND C.NR_CPF_RESPONSAVEL_CADASTRO IS NOT NULL
    ),
    PROD_ANO AS (
      SELECT
        CPF,
        EXTRACT(YEAR FROM DT_MOV) AS ANO,
        COUNT(DISTINCT NR_CONTA_CORRENTE) AS PRODUCAO_ANO
      FROM BASE_CC
      GROUP BY
        CPF,
        EXTRACT(YEAR FROM DT_MOV)
    ),
    PROD_MES AS (
      SELECT
        CPF,
        EXTRACT(YEAR FROM DT_MOV) AS ANO,
        EXTRACT(MONTH FROM DT_MOV) AS MES,
        COUNT(DISTINCT NR_CONTA_CORRENTE) AS PRODUCAO_MES
      FROM BASE_CC
      GROUP BY
        CPF,
        EXTRACT(YEAR FROM DT_MOV),
        EXTRACT(MONTH FROM DT_MOV)
    ),
    PROD_SEMANA AS (
      SELECT
        CPF,
        EXTRACT(YEAR FROM DT_MOV) AS ANO,
        COUNT(DISTINCT NR_CONTA_CORRENTE) AS PRODUCAO_SEMANAL
      FROM BASE_CC
      CROSS JOIN PARAMS PR
      WHERE DT_MOV BETWEEN TRUNC(PR.DT_INI) AND TRUNC(PR.DT_FIM)
      GROUP BY
        CPF,
        EXTRACT(YEAR FROM DT_MOV)
    ),
    CPF_NOME AS (
      SELECT
        TRIM(C.NR_CPF_RESPONSAVEL_CADASTRO) AS CPF,
        MAX(UPPER(TRIM(C.NM_USUARIO_RESPONSAVEL_CADASTRO))) AS NOME
      FROM DBACRESSEM.CONTA_CORRENTE_DIARIO_NOVO_NORMALIZADO C
      WHERE C.NR_CPF_RESPONSAVEL_CADASTRO IS NOT NULL
        AND C.NM_USUARIO_RESPONSAVEL_CADASTRO IS NOT NULL
      GROUP BY TRIM(C.NR_CPF_RESPONSAVEL_CADASTRO)
    ),
    META_ANO AS (
      SELECT 
        UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NOME,
        EXTRACT(YEAR FROM MF.DT_META) AS ANO,
        SUM(NVL(MF.QTD_META,0)) AS META_ANO
      FROM DBACRESSEM.META_FUNCIONARIOS MF
      WHERE MF.CD_PRODUTO = 8
      GROUP BY
        UPPER(TRIM(MF.NM_FUNCIONARIO)),
        EXTRACT(YEAR FROM MF.DT_META)
    ),
    FUNCIONARIOS AS (
      SELECT
        (
          SELECT MAX(TRIM(C.NR_CPF_RESPONSAVEL_CADASTRO))
          FROM DBACRESSEM.CONTA_CORRENTE_DIARIO_NOVO_NORMALIZADO C
          WHERE UPPER(TRIM(C.NM_USUARIO_RESPONSAVEL_CADASTRO))
                LIKE '%' || UPPER(TRIM(MA.NOME)) || '%'
             OR UPPER(TRIM(MA.NOME))
                LIKE '%' || UPPER(TRIM(C.NM_USUARIO_RESPONSAVEL_CADASTRO)) || '%'
        ) AS CPF,
        MA.NOME,
        AR.ANO
      FROM META_ANO MA
      CROSS JOIN ANO_REF AR
      WHERE MA.ANO = AR.ANO
    )
    SELECT
      F.CPF AS NR_CPF_RESPONSAVEL_CADASTRO,
      F.NOME AS NM_FUNCIONARIO,
      F.ANO AS ANO_REFERENCIA,
      NVL(M1.PRODUCAO_MES,0) AS PRODUCAO_JANEIRO,
      NVL(M2.PRODUCAO_MES,0) AS PRODUCAO_FEVEREIRO,
      NVL(M3.PRODUCAO_MES,0) AS PRODUCAO_MARCO,
      NVL(SW.PRODUCAO_SEMANAL,0) AS PRODUCAO_SEMANAL,
      ROUND(NVL(MA.META_ANO,0)/52) AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(MA.META_ANO,0)/52,2) > 0 THEN
          ROUND(
            (NVL(SW.PRODUCAO_SEMANAL,0) / ROUND(NVL(MA.META_ANO,0)/52,2)) * 100
          ,2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      NVL(SW.PRODUCAO_SEMANAL,0) - ROUND(NVL(MA.META_ANO,0)/52) AS GAP_SEMANAL,
      NVL(PA.PRODUCAO_ANO,0) AS PRODUCAO_ANO,
      ROUND(NVL(MA.META_ANO,0)) AS META_ANO,
      CASE
        WHEN NVL(MA.META_ANO,0) > 0 THEN
          ROUND((NVL(PA.PRODUCAO_ANO,0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      NVL(PA.PRODUCAO_ANO,0) - NVL(MA.META_ANO,0) AS FALTA_PARA_META
    FROM FUNCIONARIOS F
    CROSS JOIN PARAMS PR
    LEFT JOIN META_ANO MA
      ON MA.NOME = F.NOME
     AND MA.ANO = F.ANO
    LEFT JOIN PROD_ANO PA
      ON PA.CPF = F.CPF
     AND PA.ANO = F.ANO
    LEFT JOIN PROD_MES M1
      ON M1.CPF = F.CPF
     AND M1.ANO = F.ANO
     AND M1.MES = 1
    LEFT JOIN PROD_MES M2
      ON M2.CPF = F.CPF
     AND M2.ANO = F.ANO
     AND M2.MES = 2
    LEFT JOIN PROD_MES M3
      ON M3.CPF = F.CPF
     AND M3.ANO = F.ANO
     AND M3.MES = 3
    LEFT JOIN PROD_SEMANA SW
      ON SW.CPF = F.CPF
     AND SW.ANO = F.ANO
    ORDER BY F.NOME, F.ANO
  `;
}

function sqlSeguroVendaNova() {
  return `
    WITH
    PARAMS AS (
      SELECT
        TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
        TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA
      FROM DUAL
    ),
    PERIODO_REF AS (
      SELECT
        NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF
      FROM PARAMS
    ),
    SV_DEDUP AS (
      SELECT
        SV.NR_PA,
        TRUNC(SV.DT_VENDA) AS DT_MOV,
        SV.NR_PROPOSTA_VENDA,
        SV.NR_COOPERATIVA,
        CASE
          WHEN REGEXP_REPLACE(TRIM(SV.NR_CPF_CNPJ_ANGARIADOR), '[^0-9]', '') = '40684705885'
            THEN 'ISIS GRASIELA SANCHES RONDON'
          ELSE UPPER(TRIM(SV.NM_ANGARIADOR))
        END AS NM_FUNCIONARIO,
        MAX(NVL(SV.VL_PREMIO_MENSAL, 0)) AS VL_PREMIO_MENSAL_NUM
      FROM DBACRESSEM.SEGURO_VENDA_NOVA_ATUALIZADA SV
      WHERE SV.DT_VENDA IS NOT NULL
        AND SV.NM_ANGARIADOR IS NOT NULL
      GROUP BY
        SV.NR_PA,
        TRUNC(SV.DT_VENDA),
        SV.NR_PROPOSTA_VENDA,
        SV.NR_COOPERATIVA,
        CASE
          WHEN REGEXP_REPLACE(TRIM(SV.NR_CPF_CNPJ_ANGARIADOR), '[^0-9]', '') = '40684705885'
            THEN 'ISIS GRASIELA SANCHES RONDON'
          ELSE UPPER(TRIM(SV.NM_ANGARIADOR))
        END
    ),
    SVNA_BASE_ALL AS (
      SELECT
        CASE
          WHEN REGEXP_LIKE(TRIM(D.NR_COOPERATIVA), '^[0-9]+$')
           AND TO_NUMBER(TRIM(D.NR_COOPERATIVA)) = 4317
            THEN 4317
          WHEN REGEXP_LIKE(TRIM(D.NR_PA), '^[0-9]+$')
            THEN TO_NUMBER(TRIM(D.NR_PA))
          ELSE NULL
        END AS NR_PA,
        D.DT_MOV,
        D.NM_FUNCIONARIO,
        D.NR_PROPOSTA_VENDA,
        D.VL_PREMIO_MENSAL_NUM
      FROM SV_DEDUP D
      WHERE D.DT_MOV IS NOT NULL
        AND EXISTS (
          SELECT 1
          FROM DBACRESSEM.ANALITICO_SEGUROS_VENDA_NOVA AV
          WHERE AV.NR_PROPOSTA = D.NR_PROPOSTA_VENDA
            AND UPPER(TRIM(AV.SN_VALIDO_CNV)) = 'SIM'
            AND UPPER(TRIM(AV.NM_STATUS)) IN ('IMPLANTADA', 'ACEITA')
        )
    ),
    SVNA_BASE_UNICA AS (
      SELECT
        NR_PA,
        DT_MOV,
        NM_FUNCIONARIO,
        NR_PROPOSTA_VENDA,
        VL_PREMIO_MENSAL_NUM
      FROM (
        SELECT
          B.*,
          ROW_NUMBER() OVER (
            PARTITION BY B.NM_FUNCIONARIO, B.NR_PROPOSTA_VENDA
            ORDER BY
              CASE WHEN B.NR_PA = 4317 THEN 2 ELSE 1 END,
              B.VL_PREMIO_MENSAL_NUM DESC,
              B.DT_MOV DESC
          ) AS RN
        FROM SVNA_BASE_ALL B
      )
      WHERE RN = 1
    ),
    SVNA_BASE AS (
      SELECT
        B.*
      FROM SVNA_BASE_UNICA B
      CROSS JOIN PARAMS PR
      WHERE
        (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
        OR
        (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                     AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
    ),
    SVNA_ANO AS (
      SELECT
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
        SUM(B.VL_PREMIO_MENSAL_NUM) AS PRODUCAO_ANO
      FROM SVNA_BASE_UNICA B
      GROUP BY
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV)
    ),
    SVNA_MES AS (
      SELECT
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
        EXTRACT(MONTH FROM B.DT_MOV) AS MES,
        SUM(B.VL_PREMIO_MENSAL_NUM) AS PRODUCAO_MES
      FROM SVNA_BASE_UNICA B
      GROUP BY
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM B.DT_MOV),
        EXTRACT(MONTH FROM B.DT_MOV)
    ),
    SVNA_SEMANA AS (
      SELECT
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE)) AS ANO,
        SUM(B.VL_PREMIO_MENSAL_NUM) AS PRODUCAO_SEMANAL
      FROM SVNA_BASE B
      CROSS JOIN PARAMS PR
      GROUP BY
        B.NM_FUNCIONARIO,
        EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
    ),
    META_ANO AS (
      SELECT
        UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
        EXTRACT(YEAR FROM MF.DT_META) AS ANO,
        SUM(NVL(MF.QTD_META, 0)) AS META_ANO
      FROM DBACRESSEM.META_FUNCIONARIOS MF
      WHERE MF.CD_PRODUTO = 26
      GROUP BY
        UPPER(TRIM(MF.NM_FUNCIONARIO)),
        EXTRACT(YEAR FROM MF.DT_META)
    ),
    META_MES AS (
      SELECT
        UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
        EXTRACT(YEAR FROM MF.DT_META) AS ANO,
        EXTRACT(MONTH FROM MF.DT_META) AS MES,
        SUM(NVL(MF.QTD_META, 0)) AS META_MES
      FROM DBACRESSEM.META_FUNCIONARIOS MF
      WHERE MF.CD_PRODUTO = 26
      GROUP BY
        UPPER(TRIM(MF.NM_FUNCIONARIO)),
        EXTRACT(YEAR FROM MF.DT_META),
        EXTRACT(MONTH FROM MF.DT_META)
    ),
    SEMANAS_MES AS (
      SELECT
        EXTRACT(YEAR FROM D.DT_DIA) AS ANO,
        EXTRACT(MONTH FROM D.DT_DIA) AS MES,
        COUNT(DISTINCT TO_CHAR(D.DT_DIA, 'IW')) AS QTD_SEMANAS_MES
      FROM (
        SELECT
          TRUNC(RF.DT_REF, 'MM') + LEVEL - 1 AS DT_DIA
        FROM PERIODO_REF RF
        CONNECT BY TRUNC(RF.DT_REF, 'MM') + LEVEL - 1 <= LAST_DAY(RF.DT_REF)
      ) D
      GROUP BY
        EXTRACT(YEAR FROM D.DT_DIA),
        EXTRACT(MONTH FROM D.DT_DIA)
    ),
    BASE_FUNCIONARIOS AS (
      SELECT
        MA.NM_FUNCIONARIO,
        MA.ANO
      FROM META_ANO MA
    )
    SELECT
      BF.NM_FUNCIONARIO,
      BF.ANO,
      TO_CHAR(NVL(MJ.PRODUCAO_MES, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS PRODUCAO_VIGENTE,
      TO_CHAR(NVL(MM.META_MES, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS META_VIGENTE,
      TO_CHAR(NVL(MJ.PRODUCAO_MES, 0) - NVL(MM.META_MES, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS GAP_VIGENTE,
      TO_CHAR(NVL(SW.PRODUCAO_SEMANAL, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS PRODUCAO_SEMANAL,
      TO_CHAR(
        NVL(
          ROUND(
            NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
          , 2)
        , 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL,
      TO_CHAR(
        ROUND(NVL(MA.META_ANO, 0) / 52, 2),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(MA.META_ANO, 0) / 52, 2) > 0
          THEN ROUND(
            (NVL(SW.PRODUCAO_SEMANAL, 0) / ROUND(NVL(MA.META_ANO, 0) / 52, 2)) * 100
          , 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      TO_CHAR(
        NVL(SW.PRODUCAO_SEMANAL, 0)
        - NVL(
            ROUND(
              NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
            , 2)
          , 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS GAP_SEMANAL,
      TO_CHAR(NVL(AY.PRODUCAO_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS PRODUCAO_ANO,
      TO_CHAR(NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS META_2026,
      CASE
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO, 0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      TO_CHAR(NVL(AY.PRODUCAO_ANO, 0) - NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ ''') AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    AND MA.ANO = BF.ANO
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    AND MM.ANO = BF.ANO
    AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SEMANAS_MES SM
      ON SM.ANO = BF.ANO
    AND SM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SVNA_ANO AY
      ON AY.ANO = BF.ANO
    AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SVNA_MES MJ
      ON MJ.ANO = BF.ANO
    AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
    AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SVNA_SEMANA SW
      ON SW.ANO = BF.ANO
    AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlSeguroRural() {
  return `
    WITH
      PARAMS AS (
        SELECT
          TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
          TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA
        FROM DUAL
      ),
      PERIODO_REF AS (
        SELECT
          NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF
        FROM PARAMS
      ),
      SRC_BASE_ALL AS (
        SELECT
          SR.NR_PA,
          TRUNC(SR.DT_EMISSAO_APOLICE) AS DT_MOV,
          NVL(SR.VL_PREMIO_LIQUIDO, 0) AS VL_PREMIO_BRUTO_NUM,
          UPPER(TRIM(SR.NM_ANGARIADOR)) AS NM_FUNCIONARIO
        FROM DBACRESSEM.SEGUROS_RURAL_PRODUCAO_DIARIO SR
        WHERE SR.DT_EMISSAO_APOLICE IS NOT NULL
        UNION ALL
        SELECT
          4317 AS NR_PA,
          TRUNC(SR.DT_EMISSAO_APOLICE) AS DT_MOV,
          NVL(SR.VL_PREMIO_LIQUIDO, 0) AS VL_PREMIO_BRUTO_NUM,
          UPPER(TRIM(SR.NM_ANGARIADOR)) AS NM_FUNCIONARIO
        FROM DBACRESSEM.SEGUROS_RURAL_PRODUCAO_DIARIO SR
        WHERE SR.DT_EMISSAO_APOLICE IS NOT NULL
          AND REGEXP_LIKE(TRIM(SR.NR_COOPERATIVA), '^\\d+$')
          AND TO_NUMBER(TRIM(SR.NR_COOPERATIVA)) = 4317
      ),
      SRC_BASE AS (
        SELECT
          B.*
        FROM SRC_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          OR
          (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                       AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
      ),
      FUNCIONARIO_PA AS (
        SELECT
          X.NM_FUNCIONARIO,
          X.NR_PA
        FROM (
          SELECT
            B.NM_FUNCIONARIO,
            B.NR_PA,
            ROW_NUMBER() OVER (
              PARTITION BY B.NM_FUNCIONARIO
              ORDER BY B.DT_MOV DESC
            ) AS RN
          FROM SRC_BASE_ALL B
          WHERE B.NM_FUNCIONARIO IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      SRC_ANO AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          SUM(B.VL_PREMIO_BRUTO_NUM) AS PRODUCAO_ANO
        FROM SRC_BASE B
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      SRC_MES AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          EXTRACT(MONTH FROM B.DT_MOV) AS MES,
          SUM(B.VL_PREMIO_BRUTO_NUM) AS PRODUCAO_MES
        FROM SRC_BASE B
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV),
          EXTRACT(MONTH FROM B.DT_MOV)
      ),
      SRC_SEMANAL AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          SUM(B.VL_PREMIO_BRUTO_NUM) AS PRODUCAO_SEMANAL
        FROM SRC_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE
          (
            (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
            AND B.DT_MOV BETWEEN TRUNC(SYSDATE,'IW') AND (TRUNC(SYSDATE,'IW') + 6)
          )
          OR
          (
            (PR.DT_INI_SEMANA IS NOT NULL OR PR.DT_FIM_SEMANA IS NOT NULL)
            AND B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                            AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31')
          )
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)
      ),
      META_ANO AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          SUM(NVL(MF.QTD_META, 0)) AS META_ANO
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 24
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META)
      ),
      META_MES AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          EXTRACT(MONTH FROM MF.DT_META) AS MES,
          SUM(NVL(MF.QTD_META, 0)) AS META_MES
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 24
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META),
          EXTRACT(MONTH FROM MF.DT_META)
      ),
      SEMANAS_MES AS (
        SELECT
          ANO,
          MES,
          COUNT(DISTINCT SEMANA) AS QTD_SEMANAS_MES
        FROM (
          SELECT
            EXTRACT(YEAR FROM DT_DIA) AS ANO,
            EXTRACT(MONTH FROM DT_DIA) AS MES,
            TO_NUMBER(TO_CHAR(DT_DIA, 'IW')) AS SEMANA
          FROM (
            SELECT
              ADD_MONTHS(DATE '2020-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1) AS DT_DIA
            FROM (
              SELECT LEVEL AS NIVEL_MES FROM DUAL CONNECT BY LEVEL <= 24
            ),
            (
              SELECT LEVEL AS NIVEL_DIA FROM DUAL CONNECT BY LEVEL <= 31
            )
            WHERE ADD_MONTHS(DATE '2020-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1)
                  <= LAST_DAY(ADD_MONTHS(DATE '2020-01-01', NIVEL_MES - 1))
          )
        )
        GROUP BY ANO, MES
      ),
      BASE_FUNCIONARIOS AS (
        SELECT
          NVL(FP.NR_PA, 0) AS NR_PA,
          MA.NM_FUNCIONARIO,
          MA.ANO
        FROM META_ANO MA
        LEFT JOIN FUNCIONARIO_PA FP
          ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
      )
    SELECT
      BF.NM_FUNCIONARIO,
      BF.ANO,
      TO_CHAR(NVL(SW.PRODUCAO_SEMANAL, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_SEMANAL,
      TO_CHAR(
        NVL(
          ROUND(
            NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
          , 2)
        , 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_SEMANAL,
      ROUND(NVL(MA.META_ANO, 0) / 52, 2) AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(MA.META_ANO, 0) / 52, 2) > 0
          THEN ROUND(
            (NVL(SW.PRODUCAO_SEMANAL,0) / ROUND(NVL(MA.META_ANO, 0) / 52, 2)) * 100
          , 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      TO_CHAR(
        NVL(SW.PRODUCAO_SEMANAL,0)
        - NVL(
            ROUND(
              NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
            , 2)
          , 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS GAP_SEMANAL,
      TO_CHAR(NVL(AY.PRODUCAO_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS PRODUCAO_ANO,
      TO_CHAR(NVL(MA.META_ANO, 0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS META_2026,
      CASE
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO,0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      TO_CHAR(
        NVL(AY.PRODUCAO_ANO,0) - NVL(MA.META_ANO,0),
        'FML999G999G999G990D00',
        'NLS_NUMERIC_CHARACTERS='',.'' NLS_CURRENCY=''R$ '''
      ) AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    CROSS JOIN PARAMS PR
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MA.ANO = BF.ANO
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MM.ANO = BF.ANO
     AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SEMANAS_MES SM
      ON SM.ANO = BF.ANO
     AND SM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SRC_ANO AY
      ON AY.NR_PA = BF.NR_PA
     AND AY.ANO = BF.ANO
     AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SRC_MES MJ
      ON MJ.NR_PA = BF.NR_PA
     AND MJ.ANO = BF.ANO
     AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
     AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN SRC_SEMANAL SW
      ON SW.NR_PA = BF.NR_PA
     AND SW.ANO = BF.ANO
     AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlSaldoPrevidenciaMi() {
  return `
    WITH
      PARAMS AS (
        SELECT
          TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
          TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA
        FROM DUAL
      ),
      PERIODO_REF AS (
        SELECT
          NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF
        FROM PARAMS
      ),
      PMDN_FONTE AS (
        SELECT
          PMDN.NR_PA,
          PMDN.NR_COOPERATIVA,
          TRUNC(PMDN.DT_ADESAO) AS DT_MOV,
          PMDN.NR_MATRICULA,
          UPPER(TRIM(FSC.NM_FUNCIONARIO)) AS NM_FUNCIONARIO
        FROM DBACRESSEM.PREVIDENCIA_MI_DIARIO_NOVO PMDN
        LEFT JOIN DBACRESSEM.SICOOB_PREVI SP
          ON SP.NR_PROPOSTA = PMDN.NR_MATRICULA
        LEFT JOIN DBACRESSEM.FUNCIONARIOS_SICOOB_CRESSEM FSC
          ON UPPER(TRIM(FSC.NM_LOGIN)) = UPPER(TRIM(SP.NM_LOGIN))
        WHERE PMDN.DT_ADESAO IS NOT NULL
          AND PMDN.DESC_SITUACAO_PARTICIPANTE = 'CONTRIBUINTE'
          AND PMDN.DESC_TP_PARTICIPANTE <> 'CANCELADO'
      ),
      PMDN_BASE_ALL AS (
        SELECT
          F.NR_PA,
          F.DT_MOV,
          F.NM_FUNCIONARIO
        FROM PMDN_FONTE F
        WHERE F.NR_PA <> 4317
        UNION ALL
        SELECT
          4317 AS NR_PA,
          F.DT_MOV,
          F.NM_FUNCIONARIO
        FROM PMDN_FONTE F
        WHERE REGEXP_LIKE(TRIM(F.NR_COOPERATIVA), '^[0-9]+$')
          AND TO_NUMBER(TRIM(F.NR_COOPERATIVA)) = 4317
      ),
      PMDN_BASE AS (
        SELECT
          B.NR_PA,
          B.DT_MOV,
          B.NM_FUNCIONARIO
        FROM PMDN_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          OR
          (
            B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                         AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31')
          )
      ),
      FUNCIONARIO_PA AS (
        SELECT
          X.NM_FUNCIONARIO,
          X.NR_PA
        FROM (
          SELECT
            B.NM_FUNCIONARIO,
            B.NR_PA,
            ROW_NUMBER() OVER (
              PARTITION BY B.NM_FUNCIONARIO
              ORDER BY B.DT_MOV DESC
            ) AS RN
          FROM PMDN_BASE_ALL B
          WHERE B.NM_FUNCIONARIO IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      PMDN_ANO AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM SYSDATE) AS ANO,
          COUNT(1) AS PRODUCAO_ANO
        FROM PMDN_BASE_ALL B
        WHERE B.DT_MOV BETWEEN TRUNC(SYSDATE, 'YYYY')
                           AND SYSDATE
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM SYSDATE)
      ),
      PMDN_MES AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV) AS ANO,
          EXTRACT(MONTH FROM B.DT_MOV) AS MES,
          COUNT(1) AS PRODUCAO_MES
        FROM PMDN_BASE_ALL B
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV),
          EXTRACT(MONTH FROM B.DT_MOV)
      ),
      PMDN_SEMANA AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE)) AS ANO,
          COUNT(1) AS PRODUCAO_SEMANAL
        FROM PMDN_BASE B
        CROSS JOIN PARAMS PR
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
      ),
      META_ANO AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          SUM(NVL(MF.QTD_META, 0)) AS META_ANO
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 19
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META)
      ),
      META_MES AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          EXTRACT(MONTH FROM MF.DT_META) AS MES,
          SUM(NVL(MF.QTD_META, 0)) AS META_MES
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 19
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META),
          EXTRACT(MONTH FROM MF.DT_META)
      ),
      SEMANAS_MES AS (
        SELECT
          ANO,
          MES,
          COUNT(DISTINCT SEMANA) AS QTD_SEMANAS_MES
        FROM (
          SELECT
            EXTRACT(YEAR FROM DT_DIA) AS ANO,
            EXTRACT(MONTH FROM DT_DIA) AS MES,
            TO_NUMBER(TO_CHAR(DT_DIA, 'IW')) AS SEMANA
          FROM (
            SELECT
              ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1) AS DT_DIA
            FROM (
              SELECT LEVEL AS NIVEL_MES FROM DUAL CONNECT BY LEVEL <= 36
            ),
            (
              SELECT LEVEL AS NIVEL_DIA FROM DUAL CONNECT BY LEVEL <= 31
            )
            WHERE ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1)
                  <= LAST_DAY(ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1))
          )
        )
        GROUP BY ANO, MES
      ),
      BASE_FUNCIONARIOS AS (
        SELECT
          NVL(FP.NR_PA, 0) AS NR_PA,
          MA.NM_FUNCIONARIO,
          MA.ANO
        FROM META_ANO MA
        LEFT JOIN FUNCIONARIO_PA FP
          ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
      )
    SELECT
      BF.NM_FUNCIONARIO,
      BF.ANO,
      ROUND(NVL(MJ.PRODUCAO_MES, 0), 0) AS PRODUCAO_VIGENTE,
      ROUND(NVL(MM.META_MES, 0), 0) AS META_VIGENTE,
      ROUND(NVL(MJ.PRODUCAO_MES, 0), 0) - ROUND(NVL(MM.META_MES, 0), 0) AS GAP_VIGENTE,
      ROUND(NVL(SW.PRODUCAO_SEMANAL, 0), 0) AS PRODUCAO_SEMANAL,
      CASE
        WHEN NVL(MM.META_MES, 0) = 0 THEN 0
        ELSE CEIL(NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0))
      END AS META_SEMANAL,
      CASE
        WHEN NVL(MA.META_ANO, 0) = 0 THEN 0
        ELSE CEIL(MA.META_ANO / 52)
      END AS META_SEMANAL_52,
      CASE
        WHEN (
          CASE
            WHEN NVL(MM.META_MES, 0) = 0 THEN 0
            ELSE CEIL(NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0))
          END
        ) > 0
          THEN ROUND(
            NVL(SW.PRODUCAO_SEMANAL, 0) /
            (
              CASE
                WHEN NVL(MM.META_MES, 0) = 0 THEN 0
                ELSE CEIL(NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0))
              END
            ) * 100
          , 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      ROUND(NVL(SW.PRODUCAO_SEMANAL, 0), 0)
      - (
          CASE
            WHEN NVL(MM.META_MES, 0) = 0 THEN 0
            ELSE CEIL(NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0))
          END
        ) AS GAP_SEMANAL,
      ROUND(NVL(AY.PRODUCAO_ANO, 0), 0) AS PRODUCAO_ANO,
      ROUND(NVL(MA.META_ANO, 0), 0) AS META_ANO,
      CASE
        WHEN NVL(MA.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO, 0) / MA.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      ROUND(NVL(AY.PRODUCAO_ANO, 0), 0) - ROUND(NVL(MA.META_ANO, 0), 0) AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    CROSS JOIN PARAMS PR
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_ANO MA
      ON MA.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MA.ANO = BF.ANO
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MM.ANO = BF.ANO
     AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SEMANAS_MES SM
      ON SM.ANO = BF.ANO
     AND SM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN PMDN_ANO AY
      ON AY.NR_PA = BF.NR_PA
     AND AY.ANO = BF.ANO
     AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN PMDN_MES MJ
      ON MJ.NR_PA = BF.NR_PA
     AND MJ.ANO = BF.ANO
     AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
     AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN PMDN_SEMANA SW
      ON SW.NR_PA = BF.NR_PA
     AND SW.ANO = BF.ANO
     AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}

function sqlSaldoPrevidenciaVgbl() {
  return `
    WITH
      PARAMS AS (
        SELECT
          TO_DATE(:dt_inicio, 'DD/MM/YYYY') AS DT_INI_SEMANA,
          TO_DATE(:dt_fim, 'DD/MM/YYYY') AS DT_FIM_SEMANA
        FROM DUAL
      ),
      PERIODO_REF AS (
        SELECT
          NVL(DT_INI_SEMANA, SYSDATE) AS DT_REF
        FROM PARAMS
      ),
      PVPD_BASE_ALL AS (
        SELECT
          PVPD.NR_PA,
          TRUNC(PVPD.DT_PROPOSTA) AS DT_MOV,
          PVPD.NR_APOLICE_CERTIFICADO_SEGURO,
          PVPD.NR_COOPERATIVA,
          PVPD.DESC_PRODUTO,
          PVPD.DESC_TP_PROPOSTA,
          UPPER(TRIM(PVPD.NM_ANGARIADOR)) AS NM_FUNCIONARIO
        FROM DBACRESSEM.PREVIDENCIA_VGBL_PRODUCAO_DIARIO PVPD
        WHERE PVPD.DT_PROPOSTA IS NOT NULL
          AND PVPD.NR_PA <> 4317
          AND UPPER(TRIM(PVPD.DESC_TP_PROPOSTA)) = 'SEGURO NOVO'
          AND TRIM(PVPD.DESC_PRODUTO) <> 'SQ-NOVO PECÚLIO PREVI'
          AND PVPD.NR_APOLICE_CERTIFICADO_SEGURO IS NOT NULL
        UNION ALL
        SELECT
          4317 AS NR_PA,
          TRUNC(PVPD.DT_PROPOSTA) AS DT_MOV,
          PVPD.NR_APOLICE_CERTIFICADO_SEGURO,
          PVPD.NR_COOPERATIVA,
          PVPD.DESC_PRODUTO,
          PVPD.DESC_TP_PROPOSTA,
          UPPER(TRIM(PVPD.NM_ANGARIADOR)) AS NM_FUNCIONARIO
        FROM DBACRESSEM.PREVIDENCIA_VGBL_PRODUCAO_DIARIO PVPD
        WHERE PVPD.DT_PROPOSTA IS NOT NULL
          AND UPPER(TRIM(PVPD.DESC_TP_PROPOSTA)) = 'SEGURO NOVO'
          AND TRIM(PVPD.DESC_PRODUTO) <> 'SQ-NOVO PECÚLIO PREVI'
          AND PVPD.NR_APOLICE_CERTIFICADO_SEGURO IS NOT NULL
          AND REGEXP_LIKE(TRIM(PVPD.NR_COOPERATIVA), '^\\d+$')
          AND TO_NUMBER(TRIM(PVPD.NR_COOPERATIVA)) = 4317
      ),
      PVPD_BASE AS (
        SELECT
          B.*
        FROM PVPD_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE
          (PR.DT_INI_SEMANA IS NULL AND PR.DT_FIM_SEMANA IS NULL)
          OR
          (B.DT_MOV BETWEEN NVL(PR.DT_INI_SEMANA, DATE '1900-01-01')
                       AND NVL(PR.DT_FIM_SEMANA, DATE '2999-12-31'))
      ),
      FUNCIONARIO_PA AS (
        SELECT
          X.NM_FUNCIONARIO,
          X.NR_PA
        FROM (
          SELECT
            B.NM_FUNCIONARIO,
            B.NR_PA,
            ROW_NUMBER() OVER (
              PARTITION BY B.NM_FUNCIONARIO
              ORDER BY B.DT_MOV DESC
            ) AS RN
          FROM PVPD_BASE_ALL B
          WHERE B.NM_FUNCIONARIO IS NOT NULL
        ) X
        WHERE X.RN = 1
      ),
      PVPD_ANO AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE)) AS ANO,
          COUNT(DISTINCT B.NR_APOLICE_CERTIFICADO_SEGURO) AS PRODUCAO_ANO
        FROM PVPD_BASE_ALL B
        CROSS JOIN PARAMS PR
        WHERE B.DT_MOV BETWEEN TRUNC(NVL(PR.DT_FIM_SEMANA, SYSDATE), 'YYYY')
                           AND NVL(PR.DT_FIM_SEMANA, SYSDATE)
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
      ),
      PVPD_MES AS (
        SELECT
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV)  AS ANO,
          EXTRACT(MONTH FROM B.DT_MOV) AS MES,
          COUNT(DISTINCT B.NR_APOLICE_CERTIFICADO_SEGURO) AS PRODUCAO_MES
        FROM PVPD_BASE_ALL B
        GROUP BY
          B.NR_PA,
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM B.DT_MOV),
          EXTRACT(MONTH FROM B.DT_MOV)
      ),
      PVPD_SEMANA AS (
        SELECT
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE)) AS ANO,
          COUNT(DISTINCT B.NR_APOLICE_CERTIFICADO_SEGURO) AS PRODUCAO_SEMANAL
        FROM PVPD_BASE B
        CROSS JOIN PARAMS PR
        GROUP BY
          B.NM_FUNCIONARIO,
          EXTRACT(YEAR FROM NVL(PR.DT_FIM_SEMANA, SYSDATE))
      ),
      META_ANO AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          SUM(NVL(MF.QTD_META, 0)) AS META_ANO
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 20
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META)
      ),
      META_MES AS (
        SELECT
          UPPER(TRIM(MF.NM_FUNCIONARIO)) AS NM_FUNCIONARIO,
          EXTRACT(YEAR FROM MF.DT_META) AS ANO,
          EXTRACT(MONTH FROM MF.DT_META) AS MES,
          SUM(NVL(MF.QTD_META, 0)) AS META_MES
        FROM DBACRESSEM.META_FUNCIONARIOS MF
        WHERE MF.CD_PRODUTO = 20
        GROUP BY
          UPPER(TRIM(MF.NM_FUNCIONARIO)),
          EXTRACT(YEAR FROM MF.DT_META),
          EXTRACT(MONTH FROM MF.DT_META)
      ),
      SEMANAS_MES AS (
        SELECT
          ANO,
          MES,
          COUNT(DISTINCT SEMANA) AS QTD_SEMANAS_MES
        FROM (
          SELECT
            EXTRACT(YEAR FROM DT_DIA) AS ANO,
            EXTRACT(MONTH FROM DT_DIA) AS MES,
            TO_NUMBER(TO_CHAR(DT_DIA, 'IW')) AS SEMANA
          FROM (
            SELECT
              ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1) AS DT_DIA
            FROM (
              SELECT LEVEL AS NIVEL_MES FROM DUAL CONNECT BY LEVEL <= 36
            ),
            (
              SELECT LEVEL AS NIVEL_DIA FROM DUAL CONNECT BY LEVEL <= 31
            )
            WHERE ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1) + (NIVEL_DIA - 1)
                  <= LAST_DAY(ADD_MONTHS(DATE '2025-01-01', NIVEL_MES - 1))
          )
        )
        GROUP BY ANO, MES
      ),
      BASE_FUNCIONARIOS AS (
        SELECT
          NVL(FP.NR_PA, 0) AS NR_PA,
          MA.NM_FUNCIONARIO,
          MA.ANO,
          MA.META_ANO
        FROM META_ANO MA
        LEFT JOIN FUNCIONARIO_PA FP
          ON FP.NM_FUNCIONARIO = MA.NM_FUNCIONARIO
      )
    SELECT
      BF.NM_FUNCIONARIO,
      BF.ANO,
      ROUND(NVL(MJ.PRODUCAO_MES, 0), 0) AS PRODUCAO_VIGENTE,
      ROUND(NVL(MM.META_MES, 0), 0) AS META_VIGENTE,
      ROUND(NVL(MJ.PRODUCAO_MES, 0), 0) - ROUND(NVL(MM.META_MES, 0), 0) AS GAP_VIGENTE,
      ROUND(NVL(SW.PRODUCAO_SEMANAL, 0), 0) AS PRODUCAO_SEMANAL,
      CASE
        WHEN NVL(BF.META_ANO, 0) = 0 THEN 0
        ELSE CEIL(BF.META_ANO / 52)
      END AS META_SEMANAL_52,
      CASE
        WHEN ROUND(NVL(BF.META_ANO, 0) / 52, 0) > 0
          THEN ROUND(
            (NVL(SW.PRODUCAO_SEMANAL, 0) / ROUND(NVL(BF.META_ANO, 0) / 52, 0)) * 100
          , 2)
        ELSE 0
      END AS PORCENTAGEM_SEMANA,
      ROUND(NVL(SW.PRODUCAO_SEMANAL, 0), 0)
      - NVL(
          ROUND(
            NVL(MM.META_MES, 0) / NULLIF(NVL(SM.QTD_SEMANAS_MES, 0), 0)
          , 0)
        , 0) AS GAP_SEMANAL,
      ROUND(NVL(AY.PRODUCAO_ANO, 0), 0) AS PRODUCAO_ANO,
      ROUND(NVL(BF.META_ANO, 0), 0) AS META_2026,
      CASE
        WHEN NVL(BF.META_ANO, 0) > 0
          THEN ROUND((NVL(AY.PRODUCAO_ANO, 0) / BF.META_ANO) * 100, 2)
        ELSE 0
      END AS PERC_META_REALIZADA,
      ROUND(NVL(AY.PRODUCAO_ANO, 0), 0) - ROUND(NVL(BF.META_ANO, 0), 0) AS FALTA_PARA_META
    FROM BASE_FUNCIONARIOS BF
    CROSS JOIN PARAMS PR
    CROSS JOIN PERIODO_REF RF
    LEFT JOIN META_MES MM
      ON MM.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
     AND MM.ANO = BF.ANO
     AND MM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN SEMANAS_MES SM
      ON SM.ANO = BF.ANO
     AND SM.MES = EXTRACT(MONTH FROM RF.DT_REF)
    LEFT JOIN PVPD_ANO AY
      ON AY.NR_PA = BF.NR_PA
     AND AY.ANO = BF.ANO
     AND AY.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN PVPD_MES MJ
      ON MJ.NR_PA = BF.NR_PA
     AND MJ.ANO = BF.ANO
     AND MJ.MES = EXTRACT(MONTH FROM RF.DT_REF)
     AND MJ.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    LEFT JOIN PVPD_SEMANA SW
      ON SW.ANO = BF.ANO
     AND SW.NM_FUNCIONARIO = BF.NM_FUNCIONARIO
    ORDER BY BF.NM_FUNCIONARIO, BF.ANO
  `;
}